# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dxtmvc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5.QtWidgets import QApplication, QMainWindow, QLabel, QLineEdit, QPushButton, QVBoxLayout, QWidget, QStackedWidget, QTableWidgetItem
from controller import ProductoController
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 539)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftmenu = QtWidgets.QWidget(self.centralwidget)
        self.leftmenu.setStyleSheet("background-color: rgb(58, 71, 80\n"
");")
        self.leftmenu.setObjectName("leftmenu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftmenu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.leftmenu)
        font = QtGui.QFont()
        font.setFamily("Liberation Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.frame_2 = QtWidgets.QFrame(self.leftmenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("border:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("QFrame{\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"padding:10px 5px;\n"
"text-align:left;\n"
"border-top-left-radius:10px;\n"
"border: 1px solid rgb(48, 56, 65);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(48, 56, 65);\n"
"color: rgb(255, 255, 255);\n"
"padding:10px 5px;\n"
"text-align:left;\n"
"border-top-left-radius:10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 173, 181);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.buscarpagebtn = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(11)
        self.buscarpagebtn.setFont(font)
        self.buscarpagebtn.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/Search_Magnifying_Glass.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buscarpagebtn.setIcon(icon)
        self.buscarpagebtn.setIconSize(QtCore.QSize(24, 24))
        self.buscarpagebtn.setObjectName("buscarpagebtn")
        self.verticalLayout_3.addWidget(self.buscarpagebtn)
        self.agregarpagebtn = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.agregarpagebtn.setFont(font)
        self.agregarpagebtn.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/Add_Plus_Circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.agregarpagebtn.setIcon(icon1)
        self.agregarpagebtn.setIconSize(QtCore.QSize(24, 24))
        self.agregarpagebtn.setObjectName("agregarpagebtn")
        self.verticalLayout_3.addWidget(self.agregarpagebtn)
        self.eliminarpagebtn = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(11)
        self.eliminarpagebtn.setFont(font)
        self.eliminarpagebtn.setStyleSheet("")
        self.eliminarpagebtn.setIcon(icon)
        self.eliminarpagebtn.setIconSize(QtCore.QSize(24, 24))
        self.eliminarpagebtn.setObjectName("eliminarpagebtn")
        self.verticalLayout_3.addWidget(self.eliminarpagebtn)
        self.editarpagebtn = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        self.editarpagebtn.setFont(font)
        self.editarpagebtn.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/Edit_Pencil_01.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editarpagebtn.setIcon(icon2)
        self.editarpagebtn.setIconSize(QtCore.QSize(24, 24))
        self.editarpagebtn.setObjectName("editarpagebtn")
        self.verticalLayout_3.addWidget(self.editarpagebtn)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.leftmenu)
        self.mainbody = QtWidgets.QWidget(self.centralwidget)
        self.mainbody.setStyleSheet("background-color: rgb(48, 56, 65);")
        self.mainbody.setObjectName("mainbody")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainbody)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerframe = QtWidgets.QWidget(self.mainbody)
        self.headerframe.setObjectName("headerframe")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.headerframe)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.paginas = QtWidgets.QStackedWidget(self.headerframe)
        self.paginas.setObjectName("paginas")
        self.page_busqueda = QtWidgets.QWidget()
        self.page_busqueda.setObjectName("page_busqueda")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_busqueda)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.page_busqueda)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.frame = QtWidgets.QFrame(self.page_busqueda)
        self.frame.setStyleSheet("background-color: rgb(58, 71, 80\n"
");\n"
"border:none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.busquedainput = QtWidgets.QLineEdit(self.frame)
        self.busquedainput.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(58, 71, 80); ")
        self.busquedainput.setObjectName("busquedainput")
        self.gridLayout.addWidget(self.busquedainput, 0, 0, 1, 1)
        self.buscarbtn = QtWidgets.QPushButton(self.frame)
        self.buscarbtn.setStyleSheet("background-color: rgb(0, 173, 181);\n"
"border-radius:5px;")
        self.buscarbtn.setText("")
        self.buscarbtn.setIcon(icon)
        self.buscarbtn.setIconSize(QtCore.QSize(22, 22))
        self.buscarbtn.setObjectName("buscarbtn")
        self.gridLayout.addWidget(self.buscarbtn, 0, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(58, 71, 80); ")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 2)
        self.verticalLayout_5.addWidget(self.frame)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 8)
        self.paginas.addWidget(self.page_busqueda)
        self.page_agregarproducto = QtWidgets.QWidget()
        self.page_agregarproducto.setObjectName("page_agregarproducto")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_agregarproducto)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.page_agregarproducto)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.agregarinfo = QtWidgets.QLabel(self.page_agregarproducto)
        self.agregarinfo.setStyleSheet("color: rgb(255, 120, 0);")
        self.agregarinfo.setText("")
        self.agregarinfo.setObjectName("agregarinfo")
        self.verticalLayout_6.addWidget(self.agregarinfo)
        self.frame_4 = QtWidgets.QFrame(self.page_agregarproducto)
        self.frame_4.setStyleSheet("QFrame{\n"
"background-color: rgb(58, 71, 80\n"
");\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(38, 162, 105);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(6, 109, 2);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.nombreinput = QtWidgets.QLineEdit(self.frame_4)
        self.nombreinput.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border: 2px solid rgb(58, 71, 80); \n"
"border: 1px solid rgb(48, 56, 65);")
        self.nombreinput.setObjectName("nombreinput")
        self.gridLayout_2.addWidget(self.nombreinput, 2, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_5.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border: 2px solid rgb(58, 71, 80); \n"
"border: 1px solid rgb(48, 56, 65);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 7, 1, 1, 1)
        self.cantidadinput = QtWidgets.QLineEdit(self.frame_4)
        self.cantidadinput.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border: 2px solid rgb(58, 71, 80); \n"
"border: 1px solid rgb(48, 56, 65);")
        self.cantidadinput.setObjectName("cantidadinput")
        self.gridLayout_2.addWidget(self.cantidadinput, 5, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/Save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 8, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.talleinput = QtWidgets.QLineEdit(self.frame_4)
        self.talleinput.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border: 2px solid rgb(58, 71, 80); \n"
"border: 1px solid rgb(48, 56, 65);")
        self.talleinput.setObjectName("talleinput")
        self.gridLayout_2.addWidget(self.talleinput, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.marcainput = QtWidgets.QLineEdit(self.frame_4)
        self.marcainput.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border: 2px solid rgb(58, 71, 80); \n"
"border: 1px solid rgb(48, 56, 65);")
        self.marcainput.setObjectName("marcainput")
        self.gridLayout_2.addWidget(self.marcainput, 3, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.verticalLayout_6.setStretch(0, 2)
        self.verticalLayout_6.setStretch(2, 8)
        self.paginas.addWidget(self.page_agregarproducto)
        self.page_descontarproducto = QtWidgets.QWidget()
        self.page_descontarproducto.setObjectName("page_descontarproducto")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_descontarproducto)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.paginas.addWidget(self.page_descontarproducto)
        self.page_eliminarproducto = QtWidgets.QWidget()
        self.page_eliminarproducto.setObjectName("page_eliminarproducto")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_eliminarproducto)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.page_eliminarproducto)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.frame_6 = QtWidgets.QFrame(self.page_eliminarproducto)
        self.frame_6.setStyleSheet("background-color: rgb(58, 71, 80\n"
");\n"
"border:none;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.busquedainput_3 = QtWidgets.QLineEdit(self.frame_6)
        self.busquedainput_3.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(58, 71, 80); ")
        self.busquedainput_3.setObjectName("busquedainput_3")
        self.gridLayout_4.addWidget(self.busquedainput_3, 0, 0, 1, 1)
        self.buscarbtn_3 = QtWidgets.QPushButton(self.frame_6)
        self.buscarbtn_3.setStyleSheet("background-color: rgb(0, 173, 181);\n"
"border-radius:5px;")
        self.buscarbtn_3.setText("")
        self.buscarbtn_3.setIcon(icon)
        self.buscarbtn_3.setIconSize(QtCore.QSize(22, 22))
        self.buscarbtn_3.setObjectName("buscarbtn_3")
        self.gridLayout_4.addWidget(self.buscarbtn_3, 0, 1, 1, 1)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame_6)
        self.tableWidget_3.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(58, 71, 80); ")
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidget_3, 1, 0, 1, 2)
        self.verticalLayout_8.addWidget(self.frame_6)
        self.eliminarbtn = QtWidgets.QPushButton(self.page_eliminarproducto)
        self.eliminarbtn.setStyleSheet("background-color: rgb(224, 0, 0);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/Trash_Full.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eliminarbtn.setIcon(icon4)
        self.eliminarbtn.setIconSize(QtCore.QSize(24, 24))
        self.eliminarbtn.setObjectName("eliminarbtn")
        self.verticalLayout_8.addWidget(self.eliminarbtn)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 5)
        self.paginas.addWidget(self.page_eliminarproducto)
        self.page_editarproducto = QtWidgets.QWidget()
        self.page_editarproducto.setObjectName("page_editarproducto")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_editarproducto)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.page_editarproducto)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.frame_7 = QtWidgets.QFrame(self.page_editarproducto)
        self.frame_7.setStyleSheet("background-color: rgb(58, 71, 80\n"
");\n"
"border:none;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.busquedainput_4 = QtWidgets.QLineEdit(self.frame_7)
        self.busquedainput_4.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(58, 71, 80); ")
        self.busquedainput_4.setObjectName("busquedainput_4")
        self.gridLayout_5.addWidget(self.busquedainput_4, 0, 0, 1, 1)
        self.buscarbtn_4 = QtWidgets.QPushButton(self.frame_7)
        self.buscarbtn_4.setStyleSheet("background-color: rgb(0, 173, 181);\n"
"border-radius:5px;")
        self.buscarbtn_4.setText("")
        self.buscarbtn_4.setIcon(icon)
        self.buscarbtn_4.setIconSize(QtCore.QSize(22, 22))
        self.buscarbtn_4.setObjectName("buscarbtn_4")
        self.gridLayout_5.addWidget(self.buscarbtn_4, 0, 1, 1, 1)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.frame_7)
        self.tableWidget_4.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border-radius: 10px;\n"
"border: 2px solid rgb(58, 71, 80); ")
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableWidget_4, 1, 0, 1, 2)
        self.verticalLayout_9.addWidget(self.frame_7)
        self.frame_5 = QtWidgets.QFrame(self.page_editarproducto)
        self.frame_5.setStyleSheet("QFrame{\n"
"background-color: rgb(58, 71, 80\n"
");\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(38, 162, 105);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(6, 109, 2);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 4, 1, 1, 1)
        self.cantidadinput_2 = QtWidgets.QLineEdit(self.frame_5)
        self.cantidadinput_2.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border: 2px solid rgb(58, 71, 80); \n"
"border: 1px solid rgb(48, 56, 65);")
        self.cantidadinput_2.setObjectName("cantidadinput_2")
        self.gridLayout_3.addWidget(self.cantidadinput_2, 5, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 1, 1, 1)
        self.productoagregado_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        self.productoagregado_2.setFont(font)
        self.productoagregado_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.productoagregado_2.setText("")
        self.productoagregado_2.setAlignment(QtCore.Qt.AlignCenter)
        self.productoagregado_2.setObjectName("productoagregado_2")
        self.gridLayout_3.addWidget(self.productoagregado_2, 0, 1, 1, 2)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_6.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border: 2px solid rgb(58, 71, 80); \n"
"border: 1px solid rgb(48, 56, 65);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_3.addWidget(self.lineEdit_6, 6, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 1, 1, 1)
        self.marcainput_2 = QtWidgets.QLineEdit(self.frame_5)
        self.marcainput_2.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border: 2px solid rgb(58, 71, 80); \n"
"border: 1px solid rgb(48, 56, 65);")
        self.marcainput_2.setObjectName("marcainput_2")
        self.gridLayout_3.addWidget(self.marcainput_2, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Liberation Sans")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 5, 1, 1, 1)
        self.talleinput_2 = QtWidgets.QLineEdit(self.frame_5)
        self.talleinput_2.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border: 2px solid rgb(58, 71, 80); \n"
"border: 1px solid rgb(48, 56, 65);")
        self.talleinput_2.setObjectName("talleinput_2")
        self.gridLayout_3.addWidget(self.talleinput_2, 4, 2, 1, 1)
        self.nombreinput_2 = QtWidgets.QLineEdit(self.frame_5)
        self.nombreinput_2.setStyleSheet("background-color: rgb(238, 238, 238);\n"
"border: 2px solid rgb(58, 71, 80); \n"
"border: 1px solid rgb(48, 56, 65);")
        self.nombreinput_2.setObjectName("nombreinput_2")
        self.gridLayout_3.addWidget(self.nombreinput_2, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding: 10px;")
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 6, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_5)
        self.guardarbtneditar = QtWidgets.QPushButton(self.page_editarproducto)
        self.guardarbtneditar.setStyleSheet("background-color: rgb(38, 162, 105);")
        self.guardarbtneditar.setIcon(icon3)
        self.guardarbtneditar.setIconSize(QtCore.QSize(24, 24))
        self.guardarbtneditar.setObjectName("guardarbtneditar")
        self.verticalLayout_9.addWidget(self.guardarbtneditar)
        self.paginas.addWidget(self.page_editarproducto)
        self.horizontalLayout_2.addWidget(self.paginas)
        self.verticalLayout.addWidget(self.headerframe)
        self.mainframe = QtWidgets.QWidget(self.mainbody)
        self.mainframe.setObjectName("mainframe")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.mainframe)
        self.horizontalLayout_4.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout.addWidget(self.mainframe)
        self.horizontalLayout.addWidget(self.mainbody)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.paginas.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.buscarbtn.clicked.connect(self.buscar_productos_page_buscarproducto)
        self.buscarbtn_3.clicked.connect(self.buscar_productos_page_eliminarproducto)
        self.buscarbtn_4.clicked.connect(self.buscar_productos_page_editarproducto)
        self.pushButton.clicked.connect(self.agregar_producto)
        self.buscarpagebtn.clicked.connect(lambda: self.paginas.setCurrentWidget(self.page_busqueda))
        self.agregarpagebtn.clicked.connect(lambda: self.paginas.setCurrentWidget(self.page_agregarproducto))
        self.editarpagebtn.clicked.connect(lambda: self.paginas.setCurrentWidget(self.page_editarproducto))
        self.eliminarpagebtn.clicked.connect(lambda: self.paginas.setCurrentWidget(self.page_eliminarproducto))
        self.tableWidget_3.cellClicked.connect(self.seleccionar_fila_eliminar)
        self.tableWidget_4.cellClicked.connect(self.seleccionar_fila_editar)
        self.eliminarbtn.clicked.connect(self.eliminar_productos)
        self.guardarbtneditar.clicked.connect(self.guardar_edicion)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "DXT<br>Catalogo de productos"))
        self.buscarpagebtn.setText(_translate("MainWindow", "Busqueda de productos"))
        self.agregarpagebtn.setText(_translate("MainWindow", "Agregar producto"))
        self.eliminarpagebtn.setText(_translate("MainWindow", "Eliminar producto"))
        self.editarpagebtn.setText(_translate("MainWindow", "Editar producto"))
        self.label.setText(_translate("MainWindow", "DXT<br>Busqueda de productos"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>DXT<br/>Agregar producto</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Guadar producto"))
        self.label_6.setText(_translate("MainWindow", "Talle:"))
        self.label_4.setText(_translate("MainWindow", "Nombre:"))
        self.label_5.setText(_translate("MainWindow", "Marca:"))
        self.label_8.setText(_translate("MainWindow", "Precio:"))
        self.label_7.setText(_translate("MainWindow", "Cantidad:"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>DXT<br/>Eliminar producto</p></body></html>"))
        self.eliminarbtn.setText(_translate("MainWindow", "Eliminar producto"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>DXT<br/>Editar producto</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "Talle:"))
        self.label_14.setText(_translate("MainWindow", "Nombre:"))
        self.label_15.setText(_translate("MainWindow", "Marca:"))
        self.label_9.setText(_translate("MainWindow", "Cantidad:"))
        self.label_12.setText(_translate("MainWindow", "Precio:"))
        self.guardarbtneditar.setText(_translate("MainWindow", "Guardar producto"))

    def buscar_productos(self, busquedainput, tableWidget, columnas):
        query = busquedainput.text()
        resultados = ProductoController.buscar_productos(query)
        print(resultados)
        tableWidget.setRowCount(0)

        if not resultados:
                mensaje_item = QTableWidgetItem("No hay resultados.")
                mensaje_item.setTextAlignment(QtCore.Qt.AlignCenter)
                print(mensaje_item.text())
                tableWidget.setRowCount(1)
                tableWidget.setItem(0, 0, mensaje_item)
        else:
            print("Hay resultados")
            tableWidget.setRowCount(len(resultados))
            tableWidget.setColumnCount(len(columnas))
            tableWidget.setHorizontalHeaderLabels(columnas)

            for i, producto in enumerate(resultados):
                tableWidget.setItem(i, 0, QTableWidgetItem(str(producto.producto_id)))
                tableWidget.setItem(i, 1, QTableWidgetItem(producto.nombre))
                tableWidget.setItem(i, 2, QTableWidgetItem(producto.marca))
                tableWidget.setItem(i, 3, QTableWidgetItem(producto.talle))
                tableWidget.setItem(i, 4, QTableWidgetItem(str(producto.cantidad)))
                tableWidget.setItem(i, 5, QTableWidgetItem(str(producto.precio)))
        tableWidget.resizeColumnsToContents()

    def actualizar_tabla(self, busquedainput, tableWidget, columnas):
        self.buscar_productos(busquedainput, tableWidget, columnas)

    def agregar_producto(self):
        nombre = self.nombreinput.text()
        marca = self.marcainput.text()
        talle = self.talleinput.text()
        cantidad = self.cantidadinput.text()
        precio = self.lineEdit_5.text()


        if nombre and marca and talle and cantidad and precio:
                if not ProductoController.producto_existente(nombre, marca, talle):
                        ProductoController.agregar_producto(nombre, marca, precio, talle, cantidad)
                        self.agregarinfo.setText("Producto agregado correctamente.")
                else:
                        self.agregarinfo.setText("Error: El producto ya existe.")
        else:
                self.agregarinfo.setText("Error: Completa todos los campos.")

        self.nombreinput.clear()
        self.marcainput.clear()
        self.talleinput.clear()
        self.cantidadinput.clear()
        self.lineEdit_5.clear()

    def seleccionar_fila_eliminar(self, row, col):
        self.tableWidget_3.selectRow(row)
        selected_row = self.tableWidget_3.currentRow()
        self.eliminarpagebtn.setEnabled(selected_row != -1)

    def seleccionar_fila_editar(self, row, col):
        self.tableWidget_4.selectRow(row)
        selected_row = self.tableWidget_4.currentRow()
        self.eliminarpagebtn.setEnabled(selected_row != -1)
        if selected_row != -1:
                producto_id = int(self.tableWidget_4.item(selected_row, 0).text())
                producto = ProductoController.obtener_producto_por_id(producto_id)
                self.nombreinput_2.setText(producto.nombre)
                self.marcainput_2.setText(producto.marca)
                self.talleinput_2.setText(producto.talle)
                self.cantidadinput_2.setText(str(producto.cantidad))
                self.lineEdit_6.setText(str(producto.precio))

    def eliminar_productos(self):
        selected_row = self.tableWidget_3.currentRow()

        if selected_row != -1:
                producto_id = self.tableWidget_3.item(selected_row, 0).text()
                ProductoController.eliminar_producto(producto_id)
                self.actualizar_tabla(self.busquedainput_3, self.tableWidget_3, ["Id", "Nombre", "Marca", "Talle", "Cantidad", "Precio"])

    def buscar_productos_page_eliminarproducto(self):
        self.buscar_productos(self.busquedainput_3, self.tableWidget_3, ["Id", "Nombre", "Marca", "Talle", "Cantidad", "Precio"])

    def buscar_productos_page_buscarproducto(self):
        self.buscar_productos(self.busquedainput, self.tableWidget, ["Id", "Nombre", "Marca", "Talle", "Cantidad", "Precio"])

    def buscar_productos_page_editarproducto(self):
        self.buscar_productos(self.busquedainput_4, self.tableWidget_4, ["Id", "Nombre", "Marca", "Talle", "Cantidad", "Precio"])

    def guardar_edicion(self):
        selected_row = self.tableWidget_4.currentRow()

        if selected_row != -1:
                producto_id = int(self.tableWidget_4.item(selected_row, 0).text())
                nombre = self.nombreinput_2.text()
                marca = self.marcainput_2.text()
                talle = self.talleinput_2.text()
                cantidad = self.cantidadinput_2.text()
                precio = self.lineEdit_6.text()

                if nombre and marca and talle and cantidad and precio:
                        ProductoController.editar_producto(producto_id, nombre, marca, precio, talle, cantidad)
                        self.actualizar_tabla(self.busquedainput_4, self.tableWidget_4, ["Id", "Nombre", "Marca", "Talle", "Cantidad", "Precio"])
                        self.productoagregado_2.setText("Producto editado correctamente.")
                else:
                        self.productoagregado_2.setText("Error: Completa todos los campos.")
        else:
                mensaje_item = QTableWidgetItem("Selecciona un producto para editar.")
                mensaje_item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.tableWidget_4.setRowCount(1)
                self.tableWidget_4.setItem(0, 0, mensaje_item)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.setWindowTitle("DXT Catalogo de productos")
    MainWindow.show()
    sys.exit(app.exec_())
